In [1]:
import pandas as pd
from scipy import stats

In [2]:
df = pd.read_csv('../data/processed/df_listo_para_eda.csv', sep=';')

In [3]:
# Filtrar el dataframe para incluir todos los datos
# Asumiendo que df es tu dataframe original con todas las filas

# Separar los datos por temporada
alta = df[df['Temporada'] == 'Alta']['Viajes Ocasionales']
baja = df[df['Temporada'] == 'Baja']['Viajes Ocasionales']

# Realizar el t-test
t_stat, p_value = stats.ttest_ind(alta, baja)

# Mostrar resultados
print(f"Estadístico t: {t_stat}, Valor p: {p_value}")

# Interpretar el resultado
alpha = 0.05
if p_value <= alpha:
    print("Rechazamos la hipótesis nula. Hay una diferencia significativa en la cantidad de viajes.")
else:
    print("No podemos rechazar la hipótesis nula. No hay evidencia de una diferencia significativa.")

Estadístico t: nan, Valor p: nan
No podemos rechazar la hipótesis nula. No hay evidencia de una diferencia significativa.

In [7]:
# Supongamos que ya tienes tu dataframe llamado 'df'
# Filtrar filas que contienen al menos un NaN
df_nan = df[df.isna().any(axis=1)]

# Mostrar el dataframe filtrado
df_nan[df_nan['Region Destino']=='Tarapacá']

,CUT Comuna Origen,Comuna Origen,CUT Provincia Origen,Provincia Origen,CUT Region Origen,Region Origen,CUT Comuna Destino,Comuna Destino,Destino Turistico,CUT Provincia Destino,...,Anio,CUT Mes,Mes,Viajes Ocasionales,Temporada,PIB Region Origen,PIB Region Destino,Total Temporada Region,Total Temporada Provincia,Total Temporada Comuna
5594,1402,Camiña,14,Tamarugal,1,Tarapacá,1405,Pica,Pica,14,...,2020,1,enero,NaN,Alta,1136.354511,1136.354511,236857.0,69779.0,25128.0
5618,1402,Camiña,14,Tamarugal,1,Tarapacá,1405,Pica,Pica,14,...,2021,1,enero,NaN,Alta,1106.772123,1106.772123,171309.0,58965.0,19047.0
5648,1402,Camiña,14,Tamarugal,1,Tarapacá,1405,Pica,Pica,14,...,2022,1,enero,NaN,Alta,1173.454337,1173.454337,222964.0,81072.0,23929.0
5762,1403,Colchane,14,Tamarugal,1,Tarapacá,1402,Camiña,Camiña,14,...,2019,1,enero,NaN,Alta,1061.580205,1061.580205,272938.0,78851.0,1298.0
5764,1403,Colchane,14,Tamarugal,1,Tarapacá,1405,Pica,Pica,14,...,2019,1,enero,NaN,Alta,1061.580205,1061.580205,272938.0,78851.0,22500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6489126,16305,San Nicolás,163,Punilla,16,Ñuble,1404,Huara,Resto región Tarapacá,14,...,2023,12,diciembre,NaN,Alta,833.567298,1345.905667,246151.0,100236.0,25871.0
6489405,16305,San Nicolás,163,Punilla,16,Ñuble,1101,Iquique,Iquique,11,...,2024,12,diciembre,NaN,Alta,NaN,NaN,242742.0,128816.0,114172.0
6489406,16305,San Nicolás,163,Punilla,16,Ñuble,1107,Alto Hospicio,Resto región Tarapacá,11,...,2024,12,diciembre,NaN,Alta,NaN,NaN,242742.0,128816.0,14644.0
6489407,16305,San Nicolás,163,Punilla,16,Ñuble,1401,Pozo Almonte,Mamiña,14,...,2024,12,diciembre,NaN,Alta,NaN,NaN,242742.0,113926.0,38873.0
6489408,16305,San Nicolás,163,Punilla,16,Ñuble,1405,Pica,Pica,14,...,2024,12,diciembre,NaN,Alta,NaN,NaN,242742.0,113926.0,37022.0

In [4]:
# Verificar la cantidad de NaN por columna
nan_counts = df.isna().sum()
print(nan_counts)

CUT Comuna Origen                  0
Comuna Origen                      0
CUT Provincia Origen               0
Provincia Origen                   0
CUT Region Origen                  0
Region Origen                      0
CUT Comuna Destino                 0
Comuna Destino                     0
Destino Turistico                  0
CUT Provincia Destino              0
Provincia Destino                  0
CUT Region Destino                 0
Region Destino                     0
Anio                               0
CUT Mes                            0
Mes                                0
Viajes Ocasionales           3027301
Temporada                          0
PIB Region Origen             527820
PIB Region Destino            527820
Total Temporada Region             0
Total Temporada Provincia          0
Total Temporada Comuna             0
dtype: int64

In [12]:
# Filtrar filas donde 'PIB Region Destino' es NaN
df_nan_pib = df[df['PIB Region Destino'].isna()]

# Mostrar el dataframe filtrado
df_nan_pib.describe()

,CUT Comuna Origen,CUT Provincia Origen,CUT Region Origen,CUT Comuna Destino,CUT Provincia Destino,CUT Region Destino,Anio,CUT Mes,Viajes Ocasionales,PIB Region Origen,PIB Region Destino,Total Temporada Region,Total Temporada Provincia,Total Temporada Comuna
count,527820.000000,527820.000000,527820.000000,527820.000000,527820.000000,527820.000000,527820.0,527820.000000,56796.000000,0.0,0.0,5.278200e+05,5.278200e+05,527820.000000
mean,8956.239388,89.502205,8.720439,9048.218461,90.422371,8.814619,2024.0,9.500000,52.994507,NaN,NaN,1.206667e+06,4.401134e+05,41674.432549
std,3787.560836,37.862591,3.815943,3766.011492,37.647854,3.795079,0.0,1.707827,204.872172,NaN,NaN,6.857644e+05,4.118192e+05,49487.462543
min,1101.000000,11.000000,1.000000,1101.000000,11.000000,1.000000,2024.0,7.000000,1.000000,NaN,NaN,6.377200e+04,1.206000e+03,79.000000
25%,6107.000000,61.000000,6.000000,6111.000000,61.000000,6.000000,2024.0,8.000000,4.000000,NaN,NaN,8.682200e+05,1.288160e+05,13659.000000
50%,8304.000000,83.000000,8.000000,8313.000000,83.000000,8.000000,2024.0,9.500000,10.000000,NaN,NaN,1.089556e+06,2.878250e+05,24084.000000
75%,13107.000000,131.000000,13.000000,13107.000000,131.000000,13.000000,2024.0,11.000000,32.000000,NaN,NaN,1.677241e+06,5.593850e+05,44189.000000
max,16305.000000,163.000000,16.000000,16305.000000,163.000000,16.000000,2024.0,12.000000,11415.000000,NaN,NaN,2.547614e+06,1.570178e+06,346534.000000