In [1]:
import pandas as pd

In [20]:
df = pd.read_csv('../data/processed/df_listo_para_eda.csv',sep=';')
df.head()

,CUT Comuna Origen,Comuna Origen,CUT Provincia Origen,Provincia Origen,CUT Region Origen,Region Origen,CUT Comuna Destino,Comuna Destino,Destino Turistico,CUT Provincia Destino,...,Anio,CUT Mes,Mes,Viajes Ocasionales,Temporada,PIB Region Origen,PIB Region Destino,Total Temporada Region,Total Temporada Provincia,Total Temporada Comuna
0,1101,Iquique,11,Iquique,1,Tarapacá,1402,Camiña,Camiña,14,...,2019,1,enero,109,Alta,1061.580205,1061.580205,268129,76446,1276
1,1101,Iquique,11,Iquique,1,Tarapacá,1403,Colchane,Colchane - P.N. Volcán Isluga,14,...,2019,1,enero,298,Alta,1061.580205,1061.580205,268129,76446,5512
2,1101,Iquique,11,Iquique,1,Tarapacá,1404,Huara,Resto región Tarapacá,14,...,2019,1,enero,2594,Alta,1061.580205,1061.580205,268129,76446,22586
3,1101,Iquique,11,Iquique,1,Tarapacá,1405,Pica,Pica,14,...,2019,1,enero,4138,Alta,1061.580205,1061.580205,268129,76446,21894
4,1101,Iquique,11,Iquique,1,Tarapacá,2101,Antofagasta,Antofagasta,21,...,2019,1,enero,2071,Alta,1061.580205,3724.530431,500988,301193,187990

In [26]:
df.shape

(2952624, 22)

In [22]:
# Factorizar las variables cátegoricas, para poder hacer matriz de correlaciónes 
df['CUT Destino Turistico'] = pd.factorize(df['Destino Turistico'])[0]
df['CUT Temporada'] = pd.factorize(df['Temporada'])[0]

# Ordenar columnas
columnas = [
    'CUT Comuna Origen', 'Comuna Origen', 'CUT Provincia Origen', 'Provincia Origen',
    'CUT Region Origen', 'Region Origen', 'CUT Comuna Destino', 'Comuna Destino', 'CUT Destino Turistico',
    'Destino Turistico', 'CUT Provincia Destino', 'Provincia Destino', 'CUT Region Destino',
    'Region Destino', 'Anio', 'CUT Mes', 'Mes', 'Viajes Ocasionales', 'CUT Temporada', 'Temporada',
    'PIB Region Origen', 'PIB Region Destino', 'Total Temporada Region', 'Total Temporada Provincia', 'Total Temporada Comuna'
]

df = df[columnas]

In [23]:
df = df.drop(['Total Temporada Region','Total Temporada Provincia','Total Temporada Comuna'],axis=1)
df.head()

,CUT Comuna Origen,Comuna Origen,CUT Provincia Origen,Provincia Origen,CUT Region Origen,Region Origen,CUT Comuna Destino,Comuna Destino,CUT Destino Turistico,Destino Turistico,...,CUT Region Destino,Region Destino,Anio,CUT Mes,Mes,Viajes Ocasionales,CUT Temporada,Temporada,PIB Region Origen,PIB Region Destino
0,1101,Iquique,11,Iquique,1,Tarapacá,1402,Camiña,0,Camiña,...,1,Tarapacá,2019,1,enero,109,0,Alta,1061.580205,1061.580205
1,1101,Iquique,11,Iquique,1,Tarapacá,1403,Colchane,1,Colchane - P.N. Volcán Isluga,...,1,Tarapacá,2019,1,enero,298,0,Alta,1061.580205,1061.580205
2,1101,Iquique,11,Iquique,1,Tarapacá,1404,Huara,2,Resto región Tarapacá,...,1,Tarapacá,2019,1,enero,2594,0,Alta,1061.580205,1061.580205
3,1101,Iquique,11,Iquique,1,Tarapacá,1405,Pica,3,Pica,...,1,Tarapacá,2019,1,enero,4138,0,Alta,1061.580205,1061.580205
4,1101,Iquique,11,Iquique,1,Tarapacá,2101,Antofagasta,4,Antofagasta,...,2,Antofagasta,2019,1,enero,2071,0,Alta,1061.580205,3724.530431

In [27]:
df_num = df.drop(['Comuna Origen', 'Provincia Origen', 'Region Origen', 'Comuna Destino', 'Destino Turistico', 'Provincia Destino', 'Region Destino', 'Mes', 'Temporada'],axis=1)
df_num

,CUT Comuna Origen,CUT Provincia Origen,CUT Region Origen,CUT Comuna Destino,CUT Destino Turistico,CUT Provincia Destino,CUT Region Destino,Anio,CUT Mes,Viajes Ocasionales,CUT Temporada,PIB Region Origen,PIB Region Destino
0,1101,11,1,1402,0,14,1,2019,1,109,0,1061.580205,1061.580205
1,1101,11,1,1403,1,14,1,2019,1,298,0,1061.580205,1061.580205
2,1101,11,1,1404,2,14,1,2019,1,2594,0,1061.580205,1061.580205
3,1101,11,1,1405,3,14,1,2019,1,4138,0,1061.580205,1061.580205
4,1101,11,1,2101,4,21,2,2019,1,2071,0,1061.580205,3724.530431
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2952619,16305,163,16,16203,87,162,16,2023,12,17,0,833.567298,833.567298
2952620,16305,163,16,16207,83,162,16,2023,12,44,0,833.567298,833.567298
2952621,16305,163,16,16302,83,163,16,2023,12,108,0,833.567298,833.567298
2952622,16305,163,16,16303,83,163,16,2023,12,47,0,833.567298,833.567298
2952623,16305,163,16,16304,92,163,16,2023,12,26,0,833.567298,833.567298

In [30]:
from sklearn.model_selection import train_test_split

X = df_num.drop('Viajes Ocasionales',axis=1)
y = df_num['Viajes Ocasionales']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42)

X_train

,CUT Comuna Origen,CUT Provincia Origen,CUT Region Origen,CUT Comuna Destino,CUT Destino Turistico,CUT Provincia Destino,CUT Region Destino,Anio,CUT Mes,CUT Temporada,PIB Region Origen,PIB Region Destino
1517345,13127,131,13,4202,21,42,4,2024,6,1,21484.966717,1607.844404
675613,9211,92,9,6201,38,62,6,2020,3,1,1396.263059,2152.846770
1918278,9101,91,9,6102,34,61,6,2021,8,1,1357.975998,1773.097533
2142644,8303,83,8,9113,59,91,9,2022,9,1,2918.276976,1378.360399
2046234,4201,42,4,13121,71,131,13,2019,9,0,1470.825273,19636.899081
...,...,...,...,...,...,...,...,...,...,...,...,...
1692743,9111,91,9,14201,78,142,14,2020,7,1,1190.440147,557.384838
2356330,8102,81,8,16301,83,163,16,2020,10,1,2864.292984,733.989008
2229084,13402,134,13,9101,57,91,9,2019,9,1,19636.899081,1249.601827
2768307,5804,58,5,7203,43,72,7,2019,12,0,3427.450021,1769.897221
2219110,13131,131,13,8311,56,83,8,2019,9,1,19636.899081,2802.509087

In [31]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=42)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

print(f'El MAE es: {mean_absolute_error(y_pred,y_test)}')
print(f'El MSE es: {mean_squared_error(y_pred,y_test)}')
print(f'El R2 es: {r2_score(y_pred,y_test)}')

El MAE es: 17.998212150205323
El MSE es: 5238.385431280811
El R2 es: 0.8775853274043155

In [29]:
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

# Selección de características con SelectKBest (Ensayo y Error)
selector = SelectKBest(score_func=f_regression, k=8)
X_train_sel = selector.fit_transform(X_train, y_train)

# Transformación a los datos de test
X_test_sel = selector.transform(X_test)

# Obtener las columnas seleccionadas
selected_features = selector.get_support(indices=True)
best_columns = X.columns[selected_features]
print("Columnas seleccionadas:", best_columns)

Columnas seleccionadas: Index(['CUT Region Origen', 'CUT Comuna Destino', 'CUT Destino Turistico',
       'CUT Provincia Destino', 'CUT Region Destino', 'CUT Mes',
       'CUT Temporada', 'PIB Region Origen'],
      dtype='object')

In [17]:
# Escalar las características seleccionadas con MinMaxScaler
scaler = MinMaxScaler()
X_train_esc = scaler.fit_transform(X_train_sel) 
X_test_esc = scaler.transform(X_test_sel)  

model = RandomForestRegressor(random_state=42)
model.fit(X_train_esc,y_train)

y_pred = model.predict(X_test_esc)

print(f'El MAE es: {mean_absolute_error(y_pred,y_test)}')
print(f'El MSE es: {mean_squared_error(y_pred,y_test)}')
print(f'El R2 es: {r2_score(y_pred,y_test)}')

El MAE es: 17.74954564159011
El MSE es: 4734.908207441177
El R2 es: 0.8937420901186736

In [18]:
# Escalar las características seleccionadas con StandardScaler
scaler = StandardScaler()
X_train_esc = scaler.fit_transform(X_train_sel) 
X_test_esc = scaler.transform(X_test_sel)  

model = RandomForestRegressor(random_state=42)
model.fit(X_train_esc,y_train)

y_pred = model.predict(X_test_esc)

print(f'El MAE es: {mean_absolute_error(y_pred,y_test)}')
print(f'El MSE es: {mean_squared_error(y_pred,y_test)}')
print(f'El R2 es: {r2_score(y_pred,y_test)}')

El MAE es: 17.75544630625291
El MSE es: 4751.080069953516
El R2 es: 0.8934329934498095

In [11]:
# Escalar las características seleccionadas con RobustScaler
scaler = RobustScaler()
X_train_esc = scaler.fit_transform(X_train_sel) 
X_test_esc = scaler.transform(X_test_sel)  

model = RandomForestRegressor(random_state=42)
model.fit(X_train_esc,y_train)

y_pred = model.predict(X_test_esc)

print(f'El MAE es: {mean_absolute_error(y_pred,y_test)}')
print(f'El MSE es: {mean_squared_error(y_pred,y_test)}')
print(f'El R2 es: {r2_score(y_pred,y_test)}')

El MAE es: 54.50782399199586
El MSE es: 38648.66402038483
El R2 es: -1.383417930573441

In [14]:
from sklearn.feature_selection import SelectKBest, chi2

# Selección de características con SelectKBest (Ensayo y Error)
selector = SelectKBest(score_func=chi2, k=8)
X_train_sel = selector.fit_transform(X_train, y_train)

# Transformación a los datos de test
X_test_sel = selector.transform(X_test)

# Obtener las columnas seleccionadas
selected_features = selector.get_support(indices=True)
best_columns = X.columns[selected_features]
print("Columnas seleccionadas:", best_columns)

Columnas seleccionadas: Index(['CUT Comuna Origen', 'CUT Provincia Origen', 'CUT Region Origen',
       'CUT Comuna Destino', 'CUT Provincia Destino', 'CUT Mes',
       'PIB Region Origen', 'PIB Region Destino'],
      dtype='object')

In [15]:
scaler = MinMaxScaler()
X_train_esc = scaler.fit_transform(X_train_sel) 
X_test_esc = scaler.transform(X_test_sel)  

model = RandomForestRegressor(random_state=42)
model.fit(X_train_esc,y_train)

y_pred = model.predict(X_test_esc)

print(f'El MAE es: {mean_absolute_error(y_pred,y_test)}')
print(f'El MSE es: {mean_squared_error(y_pred,y_test)}')
print(f'El R2 es: {r2_score(y_pred,y_test)}')

El MAE es: 17.59354167901443
El MSE es: 4461.982833061089
El R2 es: 0.8978553399044686