# Explore here

In [2]:
# Your code here

import pandas as pd

In [3]:
df_viajes_totales = pd.read_csv('https://www.sernatur.cl/wp-content/uploads/2020/11/Viajes-totales-1.csv',sep=';')
df_viajes_ocasionales = pd.read_csv('https://www.sernatur.cl/wp-content/uploads/2020/11/Viajes-ocasionales-1.csv',sep=';')

In [4]:
df_viajes_ocasionales

,CUT Comuna Origen,Comuna Origen,CUT Provincia Origen,Provincia Origen,CUT Region Origen,Region Origen,CUT Comuna Destino,Comuna Destino,Destino Turistico,CUT Provincia Destino,...,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,1101,Iquique,11,Iquique,1,Tarapacá,1402,Camiña,Camiña,14,...,"33,64346123","105,9657514","99,98492432","14,97668982","25,75340796","25,38203788","117,386158","145,9445314","44,33861542","64,34864473"
1,1101,Iquique,11,Iquique,1,Tarapacá,1403,Colchane,Colchane - P.N. Volcán Isluga,14,...,"110,1058731","139,2692733","99,98492432","68,89277315","168,8278966","157,9326801","262,7214012","131,9114034","160,7274809","436,4516773"
2,1101,Iquique,11,Iquique,1,Tarapacá,1404,Huara,Resto región Tarapacá,14,...,"1064,356773","2086,011506","1521,645567","973,484838","1573,819375","6449,857847","1900,537796","1299,467655","1144,49051","1421,265718"
3,1101,Iquique,11,Iquique,1,Tarapacá,1405,Pica,Pica,14,...,"932,8414249","1653,065722","1568,5135","934,5454445","1485,113192","1613,169518","2495,853312","1403,312802","1629,444117","2039,572261"
4,1101,Iquique,11,Iquique,1,Tarapacá,2101,Antofagasta,Antofagasta,21,...,"899,1979637","1068,740293","1849,7211","748,8344908","1115,981011","1644,192009","1771,972004","1465,058566","1199,91378","1631,098256"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540801,16305,San Nicolás,163,Punilla,16,Ñuble,16203,Coelemu,Valle del Itata,162,...,"15,23200631","24,56091499","9,039206028","31,4348402","8,263839483",NaN,NaN,NaN,NaN,NaN
540802,16305,San Nicolás,163,Punilla,16,Ñuble,16207,Treguaco,Resto región Ñuble,162,...,"15,23200631","27,63102937","39,16989279","57,15425491","52,33765006",NaN,NaN,NaN,NaN,NaN
540803,16305,San Nicolás,163,Punilla,16,Ñuble,16302,Coihueco,Resto región Ñuble,163,...,"63,97442651","70,61263061","66,28751087","108,5930843","85,39300799",NaN,NaN,NaN,NaN,NaN
540804,16305,San Nicolás,163,Punilla,16,Ñuble,16303,Ñiquén,Resto región Ñuble,163,...,"36,55681515","21,49080062","12,0522747","8,573138237","27,54613161",NaN,NaN,NaN,NaN,NaN
540805,16305,San Nicolás,163,Punilla,16,Ñuble,16304,San Fabián,San Fabián,163,...,"27,41761136","15,35057187",NaN,"25,71941471","5,509226322",NaN,NaN,NaN,NaN,NaN

In [5]:
df_viajes_ocasionales.shape

(540806, 26)

In [6]:
df_viajes_ocasionales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540806 entries, 0 to 540805
Data columns (total 26 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   CUT Comuna Origen       540806 non-null  int64
 1   Comuna Origen           540806 non-null  object
 2   CUT Provincia Origen    540806 non-null  int64
 3   Provincia Origen        540806 non-null  object
 4   CUT Region Origen       540806 non-null  int64
 5   Region Origen           540806 non-null  object
 6   CUT Comuna Destino      540806 non-null  int64
 7   Comuna Destino          540806 non-null  object
 8   Destino Turistico       540806 non-null  object
 9   CUT Provincia Destino   540806 non-null  int64
 10  Provincia Destino       540806 non-null  object
 11  CUT Region Destino      540806 non-null  int64
 12  Region Destino          540806 non-null  object
 13  Anio                    540806 non-null  int64
 14  enero                   363777 non-null  object
 15  febrero                 365562 non-null  object
 16  marzo                   302075 non-null  object
 17  abril                   265877 non-null  object
 18  mayo                    276392 non-null  object
 19  junio                   270811 non-null  object
 20  julio                   308959 non-null  object
 21  agosto                  245150 non-null  object
 22  septiembre              260295 non-null  object
 23  octubre                 263942 non-null  object
 24  noviembre               257695 non-null  object
 25  diciembre               281836 non-null  object
dtypes: int64(7), object(19)
memory usage: 107.3+ MB

In [7]:
#strip es para elminar los espacios

df_viajes_totales.columns = df_viajes_totales.columns.str.strip()

In [8]:
df_viajes_totales.columns

Index(['CUT Comuna Origen', 'Comuna Origen', 'CUT Provincia Origen',
       'Provincia Origen', 'CUT Region Origen', 'Region Origen',
       'CUT Comuna Destino', 'Comuna Destino', 'Destino Turistico',
       'CUT Provincia Destino', 'Provincia Destino', 'CUT Region Destino',
       'Region Destino', 'Anio', 'enero', 'febrero', 'marzo', 'abril', 'mayo',
       'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre',
       'diciembre'],
      dtype='object')

In [9]:
df_viajes_totales['Region Destino'].head

<bound method NDFrame.head of 0            Tarapacá
1            Tarapacá
2            Tarapacá
3            Tarapacá
4         Antofagasta
             ...
550734          Ñuble
550735          Ñuble
550736          Ñuble
550737          Ñuble
550738          Ñuble
Name: Region Destino, Length: 550739, dtype: object>

In [10]:
lista_unicos_region_destino = df_viajes_totales['Region Destino'].unique().tolist()

lista_unicos_region_destino

['Tarapacá',
 'Antofagasta',
 'Atacama',
 'Coquimbo',
 'Valparaíso',
 "Libertador Gral. Bernardo O'Higgins",
 'Maule',
 'Biobío',
 'La Araucanía',
 'Los Lagos',
 'Aysén del General Carlos Ibáñez del Campo',
 'Magallanes y de la Antártica Chilena',
 'Metropolitana de Santiago',
 'Los Ríos',
 'Arica y Parinacota',
 'Ñuble']

In [11]:
# Unificar Region Destino con PIB Regional. How many turist arrive to region destination?

In [12]:
#DataSet PIB Regional

df_pib_regional = pd.read_csv('../data/raw/pib_regional.csv',encoding='ISO-8859-1', sep=';')

df_pib_regional

,Descripción series,mar.2013,jun.2013,sept.2013,dic.2013,mar.2014,jun.2014,sept.2014,dic.2014,mar.2015,...,mar.2022,jun.2022,sept.2022,dic.2022,mar.2023,jun.2023,sept.2023,dic.2023,mar.2024,jun.2024
0,Región de Arica y Parinacota,"278,30","306,13","338,48","321,35","285,12","330,56","325,58","336,35","292,84",...,"366,33","419,50","418,24","432,92","361,42","392,46","402,11","441,33","372,42","403,39"
1,Región de Tarapacá,"811,93","926,81","1.044,96","1.135,99","977,62","990,72","954,18","1.087,41","972,59",...,"1.173,45","1.206,88","1.186,95","1.218,83","1.172,44","1.155,65","1.270,08","1.345,91","1.288,44","1.261,03"
2,Región de Antofagasta,"3.759,32","3.949,00","3.792,36","4.133,68","3.803,71","4.204,01","3.887,05","4.338,46","4.075,28",...,"3.655,87","3.840,02","3.908,56","4.177,59","3.806,67","3.836,07","4.079,01","4.225,90","4.102,72","4.184,39"
3,Región de Atacama,"871,76","845,36","867,19","975,22","905,99","868,81","939,18","982,61","931,41",...,"1.004,19","980,56","955,21","1.069,10","983,43","1.026,34","1.014,97","1.070,27","1.011,94","1.000,01"
4,Región de Coquimbo,"1.426,57","1.413,42","1.341,71","1.436,15","1.386,12","1.359,61","1.264,77","1.393,83","1.332,81",...,"1.480,51","1.497,90","1.485,62","1.642,53","1.567,64","1.565,76","1.548,77","1.637,24","1.600,55","1.607,84"
5,Región de Valparaíso,"3.339,83","3.371,96","3.190,09","3.438,77","3.272,00","3.300,45","3.129,26","3.284,05","3.253,74",...,"3.672,09","3.718,33","3.622,00","3.878,09","3.686,93","3.667,86","3.654,46","3.903,45","3.755,36","3.716,73"
6,Región Metropolitana de Santiago,"16.843,14","17.862,99","17.184,75","18.822,24","17.350,24","18.063,29","17.477,48","19.130,11","17.632,26",...,"20.767,21","21.322,04","20.903,24","21.796,21","20.971,77","21.281,08","20.673,92","22.032,12","21.124,55","21.484,97"
7,Región del Libertador General Bernardo OHiggins,"1.931,43","1.708,13","1.504,86","1.694,01","1.934,95","1.700,25","1.563,98","1.782,39","2.143,62",...,"2.219,18","1.938,55","1.801,86","2.290,22","2.216,20","1.934,45","1.783,68","2.151,77","2.250,84","1.917,14"
8,Región del Maule,"1.599,50","1.610,47","1.285,82","1.467,45","1.583,32","1.558,23","1.309,13","1.541,68","1.696,49",...,"2.011,50","1.972,86","1.668,12","2.114,15","2.000,54","1.985,68","1.713,00","2.132,90","2.076,19","1.994,77"
9,Región de Ñuble,"634,64","650,65","553,33","599,95","627,80","632,39","562,57","610,57","653,45",...,"821,89","790,86","732,64","825,96","812,58","777,30","737,06","833,57","852,30","801,80"
10,Región del Biobío,"2.301,63","2.475,07","2.404,95","2.532,22","2.394,92","2.612,93","2.475,29","2.602,75","2.392,33",...,"2.939,63","3.073,57","2.918,28","3.149,52","3.088,74","3.318,56","3.137,49","3.253,03","3.174,35","3.290,04"
11,Región de La Araucanía,"1.172,64","1.068,71","1.006,80","1.084,62","1.175,24","1.091,16","1.021,65","1.112,80","1.230,25",...,"1.519,09","1.470,53","1.378,36","1.505,18","1.534,81","1.478,86","1.402,30","1.507,70","1.581,92","1.496,03"
12,Región de Los Ríos,"523,44","520,98","492,42","533,89","543,01","538,65","509,03","563,58","570,23",...,"672,22","673,39","618,62","713,05","666,27","652,35","627,15","716,07","698,00","678,85"
13,Región de Los Lagos,"1.208,47","1.237,11","1.147,30","1.311,71","1.279,23","1.343,52","1.250,16","1.401,22","1.306,79",...,"1.668,94","1.761,01","1.661,27","1.813,07","1.726,88","1.772,32","1.690,74","1.858,08","1.817,70","1.744,99"
14,Región de Aysén del General Carlos Ibáñez del ...,"282,05","272,04","265,66","279,32","276,01","288,41","271,81","301,54","281,44",...,"284,23","299,47","318,04","300,03","310,70","312,70","334,55","289,42","280,13","301,54"
15,Región de Magallanes y de la Antártica Chilena,"387,05","386,40","379,49","431,38","435,49","412,83","396,26","434,48","436,75",...,"475,58","476,47","460,02","509,35","485,58","468,91","442,94","496,16","498,07","475,59"

In [13]:
# Unificar con Región Destinno

lista_unicos_region_destino = df_viajes_totales['Region Destino'].unique().tolist()

lista_unicos_region_destino

['Tarapacá',
 'Antofagasta',
 'Atacama',
 'Coquimbo',
 'Valparaíso',
 "Libertador Gral. Bernardo O'Higgins",
 'Maule',
 'Biobío',
 'La Araucanía',
 'Los Lagos',
 'Aysén del General Carlos Ibáñez del Campo',
 'Magallanes y de la Antártica Chilena',
 'Metropolitana de Santiago',
 'Los Ríos',
 'Arica y Parinacota',
 'Ñuble']

In [14]:
lista_unicos_region_destino_pib = df_pib_regional['Descripción series'].unique().tolist()

lista_unicos_region_destino_pib

['Región de Arica y Parinacota\xa0',
 'Región de Tarapacá',
 'Región de Antofagasta',
 'Región de Atacama',
 'Región de Coquimbo',
 'Región de Valparaíso',
 'Región Metropolitana de Santiago',
 'Región del Libertador General Bernardo OHiggins',
 'Región del Maule',
 'Región de Ñuble',
 'Región del Biobío',
 'Región de La Araucanía',
 'Región de Los Ríos',
 'Región de Los Lagos',
 'Región de Aysén del General Carlos Ibáñez del Campo',
 'Región de Magallanes y de la Antártica Chilena']

In [15]:
def cambiar_nombres_regiones(df, col_nombre):
    # Diccionario que mapea los nombres originales con "Región" a los nuevos sin "Región"
    mapeo = {
        'Región de Tarapacá': 'Tarapacá',
        'Región de Antofagasta': 'Antofagasta',
        'Región de Atacama': 'Atacama',
        'Región de Coquimbo': 'Coquimbo',
        'Región de Valparaíso': 'Valparaíso',
        'Región Metropolitana de Santiago': 'Metropolitana de Santiago',
        'Región del Libertador General Bernardo OHiggins': 'Libertador General Bernardo OHiggins',
        'Región del Maule': 'Maule',
        'Región de Ñuble': 'Ñuble',
        'Región del Biobío': 'Biobío',
        'Región de La Araucanía': 'La Araucanía',
        'Región de Los Ríos': 'Los Ríos',
        'Región de Los Lagos': 'Los Lagos',
        'Región de Aysén del General Carlos Ibáñez del Campo': 'Aysén del General Carlos Ibáñez del Campo',
        'Región de Magallanes y de la Antártica Chilena': 'Magallanes y de la Antártica Chilena',
        'Región de Arica y Parinacota\xa0': 'Arica y Parinacota'
    }
    
    # Cambiar los nombres en la columna
    df[col_nombre] = df[col_nombre].replace(mapeo)
    
    # Renombrar la columna a 'Destino'
    df = df.rename(columns={col_nombre: 'Destino'})
    
    return df

In [16]:
cambiar_nombres_regiones(df_pib_regional, 'Descripción series')

,Destino,mar.2013,jun.2013,sept.2013,dic.2013,mar.2014,jun.2014,sept.2014,dic.2014,mar.2015,...,mar.2022,jun.2022,sept.2022,dic.2022,mar.2023,jun.2023,sept.2023,dic.2023,mar.2024,jun.2024
0,Arica y Parinacota,"278,30","306,13","338,48","321,35","285,12","330,56","325,58","336,35","292,84",...,"366,33","419,50","418,24","432,92","361,42","392,46","402,11","441,33","372,42","403,39"
1,Tarapacá,"811,93","926,81","1.044,96","1.135,99","977,62","990,72","954,18","1.087,41","972,59",...,"1.173,45","1.206,88","1.186,95","1.218,83","1.172,44","1.155,65","1.270,08","1.345,91","1.288,44","1.261,03"
2,Antofagasta,"3.759,32","3.949,00","3.792,36","4.133,68","3.803,71","4.204,01","3.887,05","4.338,46","4.075,28",...,"3.655,87","3.840,02","3.908,56","4.177,59","3.806,67","3.836,07","4.079,01","4.225,90","4.102,72","4.184,39"
3,Atacama,"871,76","845,36","867,19","975,22","905,99","868,81","939,18","982,61","931,41",...,"1.004,19","980,56","955,21","1.069,10","983,43","1.026,34","1.014,97","1.070,27","1.011,94","1.000,01"
4,Coquimbo,"1.426,57","1.413,42","1.341,71","1.436,15","1.386,12","1.359,61","1.264,77","1.393,83","1.332,81",...,"1.480,51","1.497,90","1.485,62","1.642,53","1.567,64","1.565,76","1.548,77","1.637,24","1.600,55","1.607,84"
5,Valparaíso,"3.339,83","3.371,96","3.190,09","3.438,77","3.272,00","3.300,45","3.129,26","3.284,05","3.253,74",...,"3.672,09","3.718,33","3.622,00","3.878,09","3.686,93","3.667,86","3.654,46","3.903,45","3.755,36","3.716,73"
6,Metropolitana de Santiago,"16.843,14","17.862,99","17.184,75","18.822,24","17.350,24","18.063,29","17.477,48","19.130,11","17.632,26",...,"20.767,21","21.322,04","20.903,24","21.796,21","20.971,77","21.281,08","20.673,92","22.032,12","21.124,55","21.484,97"
7,Libertador General Bernardo OHiggins,"1.931,43","1.708,13","1.504,86","1.694,01","1.934,95","1.700,25","1.563,98","1.782,39","2.143,62",...,"2.219,18","1.938,55","1.801,86","2.290,22","2.216,20","1.934,45","1.783,68","2.151,77","2.250,84","1.917,14"
8,Maule,"1.599,50","1.610,47","1.285,82","1.467,45","1.583,32","1.558,23","1.309,13","1.541,68","1.696,49",...,"2.011,50","1.972,86","1.668,12","2.114,15","2.000,54","1.985,68","1.713,00","2.132,90","2.076,19","1.994,77"
9,Ñuble,"634,64","650,65","553,33","599,95","627,80","632,39","562,57","610,57","653,45",...,"821,89","790,86","732,64","825,96","812,58","777,30","737,06","833,57","852,30","801,80"
10,Biobío,"2.301,63","2.475,07","2.404,95","2.532,22","2.394,92","2.612,93","2.475,29","2.602,75","2.392,33",...,"2.939,63","3.073,57","2.918,28","3.149,52","3.088,74","3.318,56","3.137,49","3.253,03","3.174,35","3.290,04"
11,La Araucanía,"1.172,64","1.068,71","1.006,80","1.084,62","1.175,24","1.091,16","1.021,65","1.112,80","1.230,25",...,"1.519,09","1.470,53","1.378,36","1.505,18","1.534,81","1.478,86","1.402,30","1.507,70","1.581,92","1.496,03"
12,Los Ríos,"523,44","520,98","492,42","533,89","543,01","538,65","509,03","563,58","570,23",...,"672,22","673,39","618,62","713,05","666,27","652,35","627,15","716,07","698,00","678,85"
13,Los Lagos,"1.208,47","1.237,11","1.147,30","1.311,71","1.279,23","1.343,52","1.250,16","1.401,22","1.306,79",...,"1.668,94","1.761,01","1.661,27","1.813,07","1.726,88","1.772,32","1.690,74","1.858,08","1.817,70","1.744,99"
14,Aysén del General Carlos Ibáñez del Campo,"282,05","272,04","265,66","279,32","276,01","288,41","271,81","301,54","281,44",...,"284,23","299,47","318,04","300,03","310,70","312,70","334,55","289,42","280,13","301,54"
15,Magallanes y de la Antártica Chilena,"387,05","386,40","379,49","431,38","435,49","412,83","396,26","434,48","436,75",...,"475,58","476,47","460,02","509,35","485,58","468,91","442,94","496,16","498,07","475,59"

In [17]:
df_pib_regional

,Descripción series,mar.2013,jun.2013,sept.2013,dic.2013,mar.2014,jun.2014,sept.2014,dic.2014,mar.2015,...,mar.2022,jun.2022,sept.2022,dic.2022,mar.2023,jun.2023,sept.2023,dic.2023,mar.2024,jun.2024
0,Arica y Parinacota,"278,30","306,13","338,48","321,35","285,12","330,56","325,58","336,35","292,84",...,"366,33","419,50","418,24","432,92","361,42","392,46","402,11","441,33","372,42","403,39"
1,Tarapacá,"811,93","926,81","1.044,96","1.135,99","977,62","990,72","954,18","1.087,41","972,59",...,"1.173,45","1.206,88","1.186,95","1.218,83","1.172,44","1.155,65","1.270,08","1.345,91","1.288,44","1.261,03"
2,Antofagasta,"3.759,32","3.949,00","3.792,36","4.133,68","3.803,71","4.204,01","3.887,05","4.338,46","4.075,28",...,"3.655,87","3.840,02","3.908,56","4.177,59","3.806,67","3.836,07","4.079,01","4.225,90","4.102,72","4.184,39"
3,Atacama,"871,76","845,36","867,19","975,22","905,99","868,81","939,18","982,61","931,41",...,"1.004,19","980,56","955,21","1.069,10","983,43","1.026,34","1.014,97","1.070,27","1.011,94","1.000,01"
4,Coquimbo,"1.426,57","1.413,42","1.341,71","1.436,15","1.386,12","1.359,61","1.264,77","1.393,83","1.332,81",...,"1.480,51","1.497,90","1.485,62","1.642,53","1.567,64","1.565,76","1.548,77","1.637,24","1.600,55","1.607,84"
5,Valparaíso,"3.339,83","3.371,96","3.190,09","3.438,77","3.272,00","3.300,45","3.129,26","3.284,05","3.253,74",...,"3.672,09","3.718,33","3.622,00","3.878,09","3.686,93","3.667,86","3.654,46","3.903,45","3.755,36","3.716,73"
6,Metropolitana de Santiago,"16.843,14","17.862,99","17.184,75","18.822,24","17.350,24","18.063,29","17.477,48","19.130,11","17.632,26",...,"20.767,21","21.322,04","20.903,24","21.796,21","20.971,77","21.281,08","20.673,92","22.032,12","21.124,55","21.484,97"
7,Libertador General Bernardo OHiggins,"1.931,43","1.708,13","1.504,86","1.694,01","1.934,95","1.700,25","1.563,98","1.782,39","2.143,62",...,"2.219,18","1.938,55","1.801,86","2.290,22","2.216,20","1.934,45","1.783,68","2.151,77","2.250,84","1.917,14"
8,Maule,"1.599,50","1.610,47","1.285,82","1.467,45","1.583,32","1.558,23","1.309,13","1.541,68","1.696,49",...,"2.011,50","1.972,86","1.668,12","2.114,15","2.000,54","1.985,68","1.713,00","2.132,90","2.076,19","1.994,77"
9,Ñuble,"634,64","650,65","553,33","599,95","627,80","632,39","562,57","610,57","653,45",...,"821,89","790,86","732,64","825,96","812,58","777,30","737,06","833,57","852,30","801,80"
10,Biobío,"2.301,63","2.475,07","2.404,95","2.532,22","2.394,92","2.612,93","2.475,29","2.602,75","2.392,33",...,"2.939,63","3.073,57","2.918,28","3.149,52","3.088,74","3.318,56","3.137,49","3.253,03","3.174,35","3.290,04"
11,La Araucanía,"1.172,64","1.068,71","1.006,80","1.084,62","1.175,24","1.091,16","1.021,65","1.112,80","1.230,25",...,"1.519,09","1.470,53","1.378,36","1.505,18","1.534,81","1.478,86","1.402,30","1.507,70","1.581,92","1.496,03"
12,Los Ríos,"523,44","520,98","492,42","533,89","543,01","538,65","509,03","563,58","570,23",...,"672,22","673,39","618,62","713,05","666,27","652,35","627,15","716,07","698,00","678,85"
13,Los Lagos,"1.208,47","1.237,11","1.147,30","1.311,71","1.279,23","1.343,52","1.250,16","1.401,22","1.306,79",...,"1.668,94","1.761,01","1.661,27","1.813,07","1.726,88","1.772,32","1.690,74","1.858,08","1.817,70","1.744,99"
14,Aysén del General Carlos Ibáñez del Campo,"282,05","272,04","265,66","279,32","276,01","288,41","271,81","301,54","281,44",...,"284,23","299,47","318,04","300,03","310,70","312,70","334,55","289,42","280,13","301,54"
15,Magallanes y de la Antártica Chilena,"387,05","386,40","379,49","431,38","435,49","412,83","396,26","434,48","436,75",...,"475,58","476,47","460,02","509,35","485,58","468,91","442,94","496,16","498,07","475,59"

In [18]:
lista_unicos_destino_turs = df_viajes_totales['Destino Turistico'].unique().tolist()

lista_unicos_destino_turs

['Camiña',
 'Colchane - P.N. Volcán Isluga',
 'Resto región Tarapacá',
 'Pica',
 'Antofagasta',
 'Mejillones',
 'Resto región Antofagasta',
 'Taltal',
 'Calama - Alto El Loa',
 'San Pedro de Atacama',
 'Tocopilla',
 'María Elena y Pedro de Valdivia',
 'Valle de Copiapó y Cordillera de Atacama',
 'Bahía inglesa - PN. Pan de Azúcar',
 'Resto región Atacama',
 'Valle del Huasco y Cetáceos del Desierto',
 'La Serena - Coquimbo',
 'Antakari',
 'Punta de Choros - R.N. Pingüino de Humboldt',
 'Valle del Elqui',
 'Valle Choapa',
 'Resto región Coquimbo',
 'Litoral Los Vilos - Pichidangui/ Quilimarí',
 'Ovalle - P.N. Fray Jorge',
 'Valles del Limarí',
 'Valparaíso',
 'Valle de Casablanca',
 'Litoral Viña del Mar - Concón',
 'Litoral Ritoque-Los Molles',
 'Rapa Nui',
 'Valle del Aconcagua',
 'Resto región Valparaíso',
 'Reserva de la Biosfera Parque Nacional La Campana.',
 'Litoral de los Poetas',
 'Cachapoal',
 "Resto región Libertador General Bernardo O'Higgins",
 'Lago Rapel',
 'Tagua Tagua - Almahue',
 'Pichilemu',
 'Valle de Colchagua',
 'Navidad',
 'Alto Colchagua',
 'Talca- Ruta Pehuenche',
 'Costa Maule',
 'Resto región Maule',
 'P.N. Radal Siete Tazas',
 'Curicó, Valle y Cordillera',
 'Maule Termal y Natural',
 'Parral                       ',
 'San Javier',
 'Concepción y alrededores',
 'Resto región Biobío',
 'Lota',
 'Tomé',
 'Lago Lanalhue',
 'Lago Lleu Lleu - Tirúa',
 'Saltos del Laja',
 'Antuco',
 'Angostura del Bíobio',
 'Alto Biobío',
 'Temuco y sus alrededores',
 'Costa Araucanía',
 'Araucanía Andina',
 'Araucanía Lacustre',
 'Resto región La Araucanía',
 'Nahuelbuta',
 'Patagonia Costa',
 'Patagonia Verde',
 'Resto región Los Lagos',
 'Lago Llanquihue y Todos Los Santos',
 'Costa Fresia - Los Muermos',
 'Archipiélago de Chiloé',
 'Osorno - Puyehue',
 'Mapu Lahual - Costa de Osorno',
 'Coyhaique y Puerto Aysén',
 'Aysén Patagonia - Queulat',
 'Provincia de Los Glaciares',
 'Chelenko',
 'Estrecho de Magallanes',
 'Cabo de Hornos y Antártica Chilena',
 'Tierra del Fuego',
 'Resto región Magallanes y de la Antártica Chilena',
 'P.N. Torres del Paine',
 'Santiago Urbano',
 'Resto región Metropolitana de Santiago',
 'Centros de Montaña',
 'Valle del Maipo',
 'Cajón del Maipo',
 'Valdivia - Corral',
 'Cuatro Ríos',
 'Resto región Los Ríos',
 'Panguipulli - Siete Lagos',
 'Cuenca del Lago Ranco',
 'Arica y costa patrimonial',
 'Codpa e iglesias patrimoniales',
 'Putre - P.N. Lauca',
 'Resto región Arica y Parinacota',
 'Chillán - Chillán Viejo',
 'Resto región Ñuble',
 'Valle de Las Trancas - Termas de Chillán',
 'Quillón',
 'Cobquecura',
 'Valle del Itata',
 'San Fabián',
 'Resto región Aysén del General Carlos Ibáñez del Campo',
 'Robinson Crusoe',
 'Iquique',
 'Mamiña']

In [19]:
df_viajes_ocasionales

,CUT Comuna Origen,Comuna Origen,CUT Provincia Origen,Provincia Origen,CUT Region Origen,Region Origen,CUT Comuna Destino,Comuna Destino,Destino Turistico,CUT Provincia Destino,...,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,1101,Iquique,11,Iquique,1,Tarapacá,1402,Camiña,Camiña,14,...,"33,64346123","105,9657514","99,98492432","14,97668982","25,75340796","25,38203788","117,386158","145,9445314","44,33861542","64,34864473"
1,1101,Iquique,11,Iquique,1,Tarapacá,1403,Colchane,Colchane - P.N. Volcán Isluga,14,...,"110,1058731","139,2692733","99,98492432","68,89277315","168,8278966","157,9326801","262,7214012","131,9114034","160,7274809","436,4516773"
2,1101,Iquique,11,Iquique,1,Tarapacá,1404,Huara,Resto región Tarapacá,14,...,"1064,356773","2086,011506","1521,645567","973,484838","1573,819375","6449,857847","1900,537796","1299,467655","1144,49051","1421,265718"
3,1101,Iquique,11,Iquique,1,Tarapacá,1405,Pica,Pica,14,...,"932,8414249","1653,065722","1568,5135","934,5454445","1485,113192","1613,169518","2495,853312","1403,312802","1629,444117","2039,572261"
4,1101,Iquique,11,Iquique,1,Tarapacá,2101,Antofagasta,Antofagasta,21,...,"899,1979637","1068,740293","1849,7211","748,8344908","1115,981011","1644,192009","1771,972004","1465,058566","1199,91378","1631,098256"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540801,16305,San Nicolás,163,Punilla,16,Ñuble,16203,Coelemu,Valle del Itata,162,...,"15,23200631","24,56091499","9,039206028","31,4348402","8,263839483",NaN,NaN,NaN,NaN,NaN
540802,16305,San Nicolás,163,Punilla,16,Ñuble,16207,Treguaco,Resto región Ñuble,162,...,"15,23200631","27,63102937","39,16989279","57,15425491","52,33765006",NaN,NaN,NaN,NaN,NaN
540803,16305,San Nicolás,163,Punilla,16,Ñuble,16302,Coihueco,Resto región Ñuble,163,...,"63,97442651","70,61263061","66,28751087","108,5930843","85,39300799",NaN,NaN,NaN,NaN,NaN
540804,16305,San Nicolás,163,Punilla,16,Ñuble,16303,Ñiquén,Resto región Ñuble,163,...,"36,55681515","21,49080062","12,0522747","8,573138237","27,54613161",NaN,NaN,NaN,NaN,NaN
540805,16305,San Nicolás,163,Punilla,16,Ñuble,16304,San Fabián,San Fabián,163,...,"27,41761136","15,35057187",NaN,"25,71941471","5,509226322",NaN,NaN,NaN,NaN,NaN

In [1]:
print("Hola Mundo!")

Hola Mundo!