In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/processed/df_listo_para_segmentar.csv',sep=';')

df

,CUT Comuna Origen,Comuna Origen,CUT Provincia Origen,Provincia Origen,CUT Region Origen,Region Origen,CUT Comuna Destino,Comuna Destino,CUT Destino Turistico,Destino Turistico,...,Anio,CUT Mes,Mes,Viajes Ocasionales,CUT Temporada,Temporada,PIB Region Origen,PIB Region Destino,Norte a Sur Origen,Norte a Sur Destino
0,1101,Iquique,11,Iquique,1,Tarapacá,1402,Camiña,0,Camiña,...,2019,1,enero,109,1,Alta,1061.580205,1061.580205,2,2
1,1101,Iquique,11,Iquique,1,Tarapacá,1403,Colchane,1,Colchane - P.N. Volcán Isluga,...,2019,1,enero,298,1,Alta,1061.580205,1061.580205,2,2
2,1101,Iquique,11,Iquique,1,Tarapacá,1404,Huara,2,Resto región Tarapacá,...,2019,1,enero,2594,1,Alta,1061.580205,1061.580205,2,2
3,1101,Iquique,11,Iquique,1,Tarapacá,1405,Pica,3,Pica,...,2019,1,enero,4138,1,Alta,1061.580205,1061.580205,2,2
4,1101,Iquique,11,Iquique,1,Tarapacá,2101,Antofagasta,4,Antofagasta,...,2019,1,enero,2071,1,Alta,1061.580205,3724.530431,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2952619,16305,San Nicolás,163,Punilla,16,Ñuble,16203,Coelemu,87,Valle del Itata,...,2023,12,diciembre,17,1,Alta,833.567298,833.567298,10,10
2952620,16305,San Nicolás,163,Punilla,16,Ñuble,16207,Treguaco,83,Resto región Ñuble,...,2023,12,diciembre,44,1,Alta,833.567298,833.567298,10,10
2952621,16305,San Nicolás,163,Punilla,16,Ñuble,16302,Coihueco,83,Resto región Ñuble,...,2023,12,diciembre,108,1,Alta,833.567298,833.567298,10,10
2952622,16305,San Nicolás,163,Punilla,16,Ñuble,16303,Ñiquén,83,Resto región Ñuble,...,2023,12,diciembre,47,1,Alta,833.567298,833.567298,10,10
2952623,16305,San Nicolás,163,Punilla,16,Ñuble,16304,San Fabián,92,San Fabián,...,2023,12,diciembre,26,1,Alta,833.567298,833.567298,10,10

In [3]:
df.shape

(2952624, 24)

In [4]:
df.columns

Index(['CUT Comuna Origen', 'Comuna Origen', 'CUT Provincia Origen',
       'Provincia Origen', 'CUT Region Origen', 'Region Origen',
       'CUT Comuna Destino', 'Comuna Destino', 'CUT Destino Turistico',
       'Destino Turistico', 'CUT Provincia Destino', 'Provincia Destino',
       'CUT Region Destino', 'Region Destino', 'Anio', 'CUT Mes', 'Mes',
       'Viajes Ocasionales', 'CUT Temporada', 'Temporada', 'PIB Region Origen',
       'PIB Region Destino', 'Norte a Sur Origen', 'Norte a Sur Destino'],
      dtype='object')

In [5]:
# Elimina las columnas 'Destino Turístico' y 'CUT Destino Turístico', 
df = df.drop(columns=['Destino Turistico', 'CUT Destino Turistico','Norte a Sur Origen', 'Norte a Sur Destino'])

In [6]:
df.head()

,CUT Comuna Origen,Comuna Origen,CUT Provincia Origen,Provincia Origen,CUT Region Origen,Region Origen,CUT Comuna Destino,Comuna Destino,CUT Provincia Destino,Provincia Destino,CUT Region Destino,Region Destino,Anio,CUT Mes,Mes,Viajes Ocasionales,CUT Temporada,Temporada,PIB Region Origen,PIB Region Destino
0,1101,Iquique,11,Iquique,1,Tarapacá,1402,Camiña,14,Tamarugal,1,Tarapacá,2019,1,enero,109,1,Alta,1061.580205,1061.580205
1,1101,Iquique,11,Iquique,1,Tarapacá,1403,Colchane,14,Tamarugal,1,Tarapacá,2019,1,enero,298,1,Alta,1061.580205,1061.580205
2,1101,Iquique,11,Iquique,1,Tarapacá,1404,Huara,14,Tamarugal,1,Tarapacá,2019,1,enero,2594,1,Alta,1061.580205,1061.580205
3,1101,Iquique,11,Iquique,1,Tarapacá,1405,Pica,14,Tamarugal,1,Tarapacá,2019,1,enero,4138,1,Alta,1061.580205,1061.580205
4,1101,Iquique,11,Iquique,1,Tarapacá,2101,Antofagasta,21,Antofagasta,2,Antofagasta,2019,1,enero,2071,1,Alta,1061.580205,3724.530431

In [11]:
df = df.drop(columns=['Provincia Origen', 'Comuna Origen', 'CUT Comuna Origen', 'CUT Provincia Origen','CUT Provincia Destino', 'Provincia Destino'])

In [14]:
# Renombrar las columnas
df = df.rename(columns={'CUT Temporada': 'Num Temporada', 'CUT Mes': 'Num Mes'})

df

,CUT Region Origen,Region Origen,CUT Comuna Destino,Comuna Destino,CUT Region Destino,Region Destino,Anio,Num Mes,Mes,Viajes Ocasionales,Num Temporada,Temporada,PIB Region Origen,PIB Region Destino
0,1,Tarapacá,1402,Camiña,1,Tarapacá,2019,1,enero,109,1,Alta,1061.580205,1061.580205
1,1,Tarapacá,1403,Colchane,1,Tarapacá,2019,1,enero,298,1,Alta,1061.580205,1061.580205
2,1,Tarapacá,1404,Huara,1,Tarapacá,2019,1,enero,2594,1,Alta,1061.580205,1061.580205
3,1,Tarapacá,1405,Pica,1,Tarapacá,2019,1,enero,4138,1,Alta,1061.580205,1061.580205
4,1,Tarapacá,2101,Antofagasta,2,Antofagasta,2019,1,enero,2071,1,Alta,1061.580205,3724.530431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2952619,16,Ñuble,16203,Coelemu,16,Ñuble,2023,12,diciembre,17,1,Alta,833.567298,833.567298
2952620,16,Ñuble,16207,Treguaco,16,Ñuble,2023,12,diciembre,44,1,Alta,833.567298,833.567298
2952621,16,Ñuble,16302,Coihueco,16,Ñuble,2023,12,diciembre,108,1,Alta,833.567298,833.567298
2952622,16,Ñuble,16303,Ñiquén,16,Ñuble,2023,12,diciembre,47,1,Alta,833.567298,833.567298
2952623,16,Ñuble,16304,San Fabián,16,Ñuble,2023,12,diciembre,26,1,Alta,833.567298,833.567298

In [15]:
df.columns

Index(['CUT Region Origen', 'Region Origen', 'CUT Comuna Destino',
       'Comuna Destino', 'CUT Region Destino', 'Region Destino', 'Anio',
       'Num Mes', 'Mes', 'Viajes Ocasionales', 'Num Temporada', 'Temporada',
       'PIB Region Origen', 'PIB Region Destino'],
      dtype='object')

In [17]:
# Definir el nuevo orden de las columnas

column_order = ['CUT Region Origen', 'Region Origen', 'CUT Region Destino', 'Region Destino', 
                'CUT Comuna Destino', 'Comuna Destino', 'Anio', 'Num Mes', 'Mes', 
                'Num Temporada', 'Temporada', 'Viajes Ocasionales', 'PIB Region Origen', 
                'PIB Region Destino']

# Reordenar las columnas en el DataFrame
df = df[column_order]

df

,CUT Region Origen,Region Origen,CUT Region Destino,Region Destino,CUT Comuna Destino,Comuna Destino,Anio,Num Mes,Mes,Num Temporada,Temporada,Viajes Ocasionales,PIB Region Origen,PIB Region Destino
0,1,Tarapacá,1,Tarapacá,1402,Camiña,2019,1,enero,1,Alta,109,1061.580205,1061.580205
1,1,Tarapacá,1,Tarapacá,1403,Colchane,2019,1,enero,1,Alta,298,1061.580205,1061.580205
2,1,Tarapacá,1,Tarapacá,1404,Huara,2019,1,enero,1,Alta,2594,1061.580205,1061.580205
3,1,Tarapacá,1,Tarapacá,1405,Pica,2019,1,enero,1,Alta,4138,1061.580205,1061.580205
4,1,Tarapacá,2,Antofagasta,2101,Antofagasta,2019,1,enero,1,Alta,2071,1061.580205,3724.530431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2952619,16,Ñuble,16,Ñuble,16203,Coelemu,2023,12,diciembre,1,Alta,17,833.567298,833.567298
2952620,16,Ñuble,16,Ñuble,16207,Treguaco,2023,12,diciembre,1,Alta,44,833.567298,833.567298
2952621,16,Ñuble,16,Ñuble,16302,Coihueco,2023,12,diciembre,1,Alta,108,833.567298,833.567298
2952622,16,Ñuble,16,Ñuble,16303,Ñiquén,2023,12,diciembre,1,Alta,47,833.567298,833.567298
2952623,16,Ñuble,16,Ñuble,16304,San Fabián,2023,12,diciembre,1,Alta,26,833.567298,833.567298

In [28]:
df_grouped = df.groupby(['Region Origen', 'Comuna Destino', 'Anio', 'Mes'], as_index=False).agg({
    'Viajes Ocasionales': 'sum',          # Sumar los viajes ocasionales
    'PIB Region Origen': 'first',         # Mantener el primer valor del PIB según la región de origen
    'PIB Region Destino': 'first',        # Mantener el primer valor del PIB según la región de destino
    'Temporada': 'first'                  # Tomar la temporada correspondiente según el mes y año
})

df_grouped

,Region Origen,Comuna Destino,Anio,Mes,Viajes Ocasionales,PIB Region Origen,PIB Region Destino,Temporada
0,Antofagasta,Aisén,2019,abril,13,3894.124564,308.139915,Baja
1,Antofagasta,Aisén,2019,agosto,12,4099.144469,314.027098,Baja
2,Antofagasta,Aisén,2019,diciembre,10,4279.561800,315.639897,Alta
3,Antofagasta,Aisén,2019,enero,52,3724.530431,296.813161,Alta
4,Antofagasta,Aisén,2019,febrero,45,3724.530431,296.813161,Alta
...,...,...,...,...,...,...,...,...
290149,Ñuble,Ñuñoa,2024,enero,636,852.296102,21124.552771,Alta
290150,Ñuble,Ñuñoa,2024,febrero,599,852.296102,21124.552771,Alta
290151,Ñuble,Ñuñoa,2024,junio,684,801.797197,21484.966717,Baja
290152,Ñuble,Ñuñoa,2024,marzo,998,852.296102,21124.552771,Baja
290153,Ñuble,Ñuñoa,2024,mayo,687,801.797197,21484.966717,Baja

In [31]:
# Hacemos el merge entre el df original y el df_grouped usando las columnas clave
df_merged = pd.merge(
    df, df_grouped, 
    on=['Region Origen', 'Comuna Destino', 'Anio', 'Mes'], 
    how='left',  # Usamos 'left' para mantener todas las filas de df original
    suffixes=('_original', '_grouped')  # Para distinguir las columnas duplicadas, si las hay
)

df_merged

,CUT Region Origen,Region Origen,CUT Region Destino,Region Destino,CUT Comuna Destino,Comuna Destino,Anio,Num Mes,Mes,Num Temporada,Temporada_original,Viajes Ocasionales_original,PIB Region Origen_original,PIB Region Destino_original,Viajes Ocasionales_grouped,PIB Region Origen_grouped,PIB Region Destino_grouped,Temporada_grouped
0,1,Tarapacá,1,Tarapacá,1402,Camiña,2019,1,enero,1,Alta,109,1061.580205,1061.580205,353,1061.580205,1061.580205,Alta
1,1,Tarapacá,1,Tarapacá,1403,Colchane,2019,1,enero,1,Alta,298,1061.580205,1061.580205,1804,1061.580205,1061.580205,Alta
2,1,Tarapacá,1,Tarapacá,1404,Huara,2019,1,enero,1,Alta,2594,1061.580205,1061.580205,4707,1061.580205,1061.580205,Alta
3,1,Tarapacá,1,Tarapacá,1405,Pica,2019,1,enero,1,Alta,4138,1061.580205,1061.580205,6598,1061.580205,1061.580205,Alta
4,1,Tarapacá,2,Antofagasta,2101,Antofagasta,2019,1,enero,1,Alta,2071,1061.580205,3724.530431,2866,1061.580205,3724.530431,Alta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2952619,16,Ñuble,16,Ñuble,16203,Coelemu,2023,12,diciembre,1,Alta,17,833.567298,833.567298,452,833.567298,833.567298,Alta
2952620,16,Ñuble,16,Ñuble,16207,Treguaco,2023,12,diciembre,1,Alta,44,833.567298,833.567298,315,833.567298,833.567298,Alta
2952621,16,Ñuble,16,Ñuble,16302,Coihueco,2023,12,diciembre,1,Alta,108,833.567298,833.567298,429,833.567298,833.567298,Alta
2952622,16,Ñuble,16,Ñuble,16303,Ñiquén,2023,12,diciembre,1,Alta,47,833.567298,833.567298,1021,833.567298,833.567298,Alta
2952623,16,Ñuble,16,Ñuble,16304,San Fabián,2023,12,diciembre,1,Alta,26,833.567298,833.567298,1964,833.567298,833.567298,Alta

In [33]:
# Filtramos el DataFrame para obtener solo las filas correspondientes a la comuna de destino 'Comuna X'
comuna_especifica = df[df['Comuna Destino'] == 'Camiña']

# Mostrar todo el contenido de 'comuna_especifica'
comuna_especifica

,CUT Region Origen,Region Origen,CUT Region Destino,Region Destino,CUT Comuna Destino,Comuna Destino,Anio,Num Mes,Mes,Num Temporada,Temporada,Viajes Ocasionales,PIB Region Origen,PIB Region Destino
0,1,Tarapacá,1,Tarapacá,1402,Camiña,2019,1,enero,1,Alta,109,1061.580205,1061.580205
238,1,Tarapacá,1,Tarapacá,1402,Camiña,2020,1,enero,1,Alta,96,1136.354511,1136.354511
421,1,Tarapacá,1,Tarapacá,1402,Camiña,2021,1,enero,1,Alta,63,1106.772123,1106.772123
676,1,Tarapacá,1,Tarapacá,1402,Camiña,2022,1,enero,1,Alta,134,1173.454337,1173.454337
944,1,Tarapacá,1,Tarapacá,1402,Camiña,2023,1,enero,1,Alta,698,1172.444308,1172.444308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2940439,15,Arica y Parinacota,1,Tarapacá,1402,Camiña,2021,12,diciembre,1,Alta,108,437.223524,1266.517443
2940682,15,Arica y Parinacota,1,Tarapacá,1402,Camiña,2022,12,diciembre,1,Alta,59,432.919088,1218.831306
2940928,15,Arica y Parinacota,1,Tarapacá,1402,Camiña,2023,12,diciembre,1,Alta,48,441.328576,1345.905667
2941188,15,Arica y Parinacota,1,Tarapacá,1402,Camiña,2021,12,diciembre,1,Alta,2,437.223524,1266.517443
2941202,15,Arica y Parinacota,1,Tarapacá,1402,Camiña,2023,12,diciembre,1,Alta,4,441.328576,1345.905667